### ISSUE TITLE
Additional Mod Compatibility

### ISSUE THREAD

**Issue by TrueDakkon** [Farcr/SwampExpansion#57]
It would be great if you could add some additional compatibility for mods like Enhanced Vanilla and BiomesO'Plenty. Things like your mods cattails and trees should override the BoP ones and should be able to be placed on things like their mud blocks. Right now the cattails cannot be placed on the mud blocks from BoP or EV which makes it hard to use them as swamp biomes when using BoP consist of primarily these mud blocks.
As a side note, you added rice, and as of yet I have no idea where you can get this inside of the swamps. I have searched pretty far and through several swamps and still as of yet do not know where you can get the rice seeds. I Think a grass or something specific to swamps would be good to have them drop from.

**Comment by bageldotjpg** [comment]
If they tag their blocks correctly they can be placed on them.
Rice generate inside of Marsh biomes.
Overriding BoP features would be hard to do and will be able to be configured with datapacks in 1.16.3.

Also, this mod is abandoned due to its merge with Bloomful to make Environmental, which will be releasing soon,
